# Generated by Django 4.2.5 on 2023-11-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditor', models.CharField(max_length=250)),
                ('dateCreated', models.CharField()),
                ('debtor', models.CharField()),
                ('amount', models.IntegerField()),
                ('dateDue', models.CharField()),
                ('description', models.TextField(max_length=250)),
            ],
        ),
    ]
