# Generated by Django 4.2.5 on 2023-11-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='creditor',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='loan',
            name='dateCreated',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='loan',
            name='dateDue',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='loan',
            name='debtor',
            field=models.TextField(max_length=100),
        ),
    ]
