# Generated by Django 4.2.5 on 2023-11-30 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_loan_datecreated_alter_loan_datedue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='creditor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='debtor',
            field=models.IntegerField(),
        ),
    ]
