# Generated by Django 4.2.5 on 2023-12-12 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_debt_creditor_alter_debt_datecreated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='creditor',
        ),
    ]
