# Generated by Django 4.2.5 on 2023-12-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_loan_creditor'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='creditor',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
