# Generated by Django 4.2.5 on 2023-12-13 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_loan_creditor'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='debtor',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
